api/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from .views import *
from core.views import get_phone_ajax, rank_worker_ajax, set_status_we_ajax, send_pin_ajax
from rest_framework.urlpatterns import format_suffix_patterns

from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'categories', ServiceCategoryViewSet, 'categories')
router.register(r'users', SimpleUserView, 'users')
router.register(r'workerevaluation', WorkerEvaluationView, 'workerevaluation')
router.register(r'workers', WorkersViewSet)
router.register(r'places', PlaceViewSet, 'places')
router.register(r'phones', PhoneViewSet, 'phones')

urlpatterns = [
    # Routers urls
    url(r'^', include(router.urls)),

    # Categories
    url('^categories-resume', ServiceCategoryResume.as_view(), name='categories-resume'),

    # professionals
    url ('^professionals/(?P<id>.+)/$', ProfessionalList.as_view(), name='professionals'),
    url ('^professional/(?P<pk>.+)/$', ProfessionalDetails.as_view(), name='professional-details'),

    # User profiles
    url('^user/profile/$',LoggedUserProfile.as_view()),   

    url('^service-description/$', ServiceTypeViewSet.as_view()),
    url('^service-description/(?P<id>[0-9]+)/$', ServiceTypeSpecificViewSet.as_view()),

    # Authentication urls
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    # Templates urls
    url('^template/(?P<pk>.+)/$', EvaluationTemplateByCategory.as_view(),name="template-detail"),

    # Services urls
    url('^all-services/$',ServiceCategoryComplete.as_view()),
    url('^services/$',ServiceCategoryList.as_view()),
    url('^dateservices/(?P<mes>[0-9]+)/(?P<ano>[0-9]+)/(?P<worker>[0-1])/(?P<userId>[0-9]+)/?$', DateServiceRequestList.as_view(), name='date-service-list'),

    # Agendamentos
    url('^agendamentos/(?P<pk>.+)/$', ServiceRequestRetrieveUpdate.as_view(),name="service-details"),
    url('^agendamentos/$', ServiceRequestView.as_view(), name='agendamento-list'),
    url('^criar-agendamento/$', ServiceRequestCreateView.as_view(), name='criar-agendamento'),
    url('^todos-agendamentos/$', ServiceRequestComplete.as_view(), name='todos-agendamentos'),

    # Notifications
    url('^notifications/$', NotificationList.as_view(), name='notification-list'),
    url('^notifications/(?P<pk>.+)/$', NotificationDetails.as_view(), name='notification-details'),

    # Messages
    url('^messages/(?P<id>[0-9])/$', ServiceMessageListCreate.as_view(), name='msg-list-update'),
    url('^messages/(?P<id>[0-9])/latest/$', LatestServiceMessageList.as_view(), name='msg-latest'),
    url('^messages/(?P<pk>[0-9])/last/$', LastServiceMessage.as_view(),name="msg-last"),


    url ('^example/$', ExampleView.as_view(), name='example'),

    #Ajax
    url('^ajax/get-phone-user/$', get_phone_ajax, name='get_phone_ajax'),
    url('^ajax/rank-worker/$', rank_worker_ajax, name='rank_worker_ajax'),
    url('^ajax/set-status-we/$', set_status_we_ajax, name='set_status_we_ajax'),
    url('^ajax/send_pin_ajax/$', send_pin_ajax, name='send_pin_ajax'),
]

hirer/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    
    url(r'^profissional/(?P<id>[0-9]+)/$',
        views.professional_details, name='professional-details'),
    url(r'^agendamento/(?P<service_provided>[0-9]+)/?$',
        views.service_request_create, name='service-request-create'),
    url(r'^profissionais/(?P<category>[0-9]+)/$',
        views.professionals, name='professionals'),
    url(r'^agenda/$', views.full_schedule, name='schedule'),
    url(r'^friend/recommendations/(?P<worker>[0-9]+)/$',
        views.friends_recommendations, name='friend-recommendations'),
    url(r'^schedule/evaluate_worker/',
        views.evaluate_worker_ex, name='evaluate_worker'),
    url(r'^service/end/(?P<id>[0-9]+)/$', views.evaluate_service,
        name='finish-service'),
    url(r'^evaluate/(?P<id>[0-9]+)/$',
        views.evaluate_worker_ex, name='evaluate'),
    url(r'^schedule/get_day_service/', views.get_day_service, name='get_day_service'),
]

indico/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
import rest_auth
from hirer import views
import certbot_django.server.urls

urlpatterns = [
    # Examples:
    # url(r'^$', 'indico.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),

    url ('', include('public.urls', namespace='indico')),
    url (r'^hirer/', include('hirer.urls', namespace='hirer')),
    url (r'^profissional/', include('worker.urls', namespace='worker')),
    url (r'^usuario/', include('core.urls', namespace='core')),
    url (r'^api/v1/', include('api.urls', namespace='api_v1')),

    url(r'^reset/done/$', 'password_reset.views.reset_done', name='password_reset_done'),

    url('', include('social.apps.django_app.urls', namespace='social')),
    url('', include('django.contrib.auth.urls', namespace='auth')),
    url(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    url('', include('password_reset.urls')),
    url(r'^.well-known/acme-challenge/(?P<token>.+)/$', views.acme),
    url(r'^rest-auth/', include('rest_auth.urls')),
    url(r'^accounts/', include('allauth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hirer/views.py
# -*- coding: utf-8 -*-
from django.contrib.auth.decorators import login_required
from core.models import (ServiceCategory, IndicoUser, EvaluationTemplate, EvaluationTemplateItem,
                         ServiceRequest, EvaluationParameter, Notification, Endorsment, WorkerEvaluation,
                         WorkerEvaluationItem,Place, ServiceProvided)

from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

from .forms import ServiceRequestForm
from .forms import EvaluationForm
from .forms import SearchWorkerForm
from .forms import EvaluationProfessionalForm
from core.utils import get_encoded_id
from django.db.models import Q
from core.constants import *
from django.core.mail import send_mail
from core.utils import *

@login_required
#@permission_required(['app.contractor_pass'], raise_exception= True)
def home(request):
    """
    Acesso a home de clientes
    """
    categories = ServiceCategory.get_active_categories()

    if not categories:
        return render (request, 'hirer/home.html', {'groups':None})

    groups = dict()
    for category in categories:
        if category.group in groups:
            groups[category.group].append(category)
        else:
            groups[category.group] = [category]

    return render (request, 'hirer/home.html', {'groups':groups})

class WorkerDTO:
    def __init__(self, **kwargs):
        self.__dict__ = kwargs

@login_required
def professionals(request, category, template_name='hirer/professionals.html'):
    """
    Atualmente esse método renderiza um lista aleatória de trabalhadores
    cadastrados no sistema.
    """
    cat = ServiceCategory.objects.get(pk=category)
    skills = cat.skill_set.all()
    workers = IndicoUser.objects.professionals_by_category(cat)
    neighborhoods = []
    for w in workers:
        places = Place.objects.filter(owner=w)
        if places:
            for p in places:
                nh = p.neighborhood
                if not nh in neighborhoods:
                    neighborhoods.append(nh)

    data = {
        "category" : cat.id,
        "categoryname": cat.description,
        "skills":skills,
        "neighborhoods":sorted(neighborhoods),
    }

    return render (request, template_name, data)

@login_required
def friends_recommendations (request, worker,template_name='partials/_hirer_friends.html'):
    queryset = Endorsment.friends_that_recommends(request.user, worker)
    total = queryset.count()
    friends = queryset[:4]

    data = {
        'total':total,
        'friends':friends
    }

    return render (request, template_name, data)

@login_required
def service_request_create (request, service_provided, template_name="hirer/servicerequest-create.html"):
    """
    Cria novas requisições de serviço
    """
    service_provided = ServiceProvided.objects.get(id = service_provided)

    #worker = IndicoUser.objects.get(id = professional)
    if request.method == 'POST':
        form = ServiceRequestForm(data =request.POST)
        if form.is_valid():
            new_service_request = form.save()
            request.user.phone_number = form.cleaned_data['phone_number']
            request.user.save()

            notification = Notification.objects.newRequest(service_provided.worker,"Nova solicitação de serviço cod. " + str(new_service_request.id))
            notification.save()

            #Send an alert by email
            send_mail(
                "[Indikko] Alerta de Novo Serviço", alert_new_service_notification(request.user, service_provided.worker, new_service_request),
                'suporte@indikko.com', [service_provided.worker.email], fail_silently=True)
            return redirect('hirer:home')
        else:
            form.fields['address'].queryset = Place.objects.filter (owner = request.user)
            print ('formulario invalido!!!')
            print (form.errors)
    else:
        data = {'owner': request.user.id,
                'professional': service_provided.worker.id,
                'category':service_provided.service_type.service_category.id,
                'price': service_provided.price,
                'phone_number': request.user.phone_number,
                'service_provided': service_provided
            }

        form = ServiceRequestForm(owner = request.user, initial=data)

    service_category = ServiceCategory.objects.get(pk = service_provided.service_type.service_category.id)
    form_data = {
        'form': form,
        'p' : IndicoUser.objects.get(pk=service_provided.worker.id),
        'sp': service_provided
    }

    return render (request, template_name, form_data)

@login_required
def full_schedule(request, template_name='hirer/full-schedule.html'):
    context_data = {
        'user': request.user,
    }

    return render(request, template_name, context_data)


def evaluate_worker(request):

    if request.method == 'POST':
        form = EvaluationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('hirer:home')
    else:
        id = request.GET['id']
        service = get_object_or_404(ServiceRequest, pk=id)
        params = {'service': service, 'hirer': service.owner, 'worker': service.service_provided.worker, 'indicate': True}

        try:
            evaluation = WorkerEvaluation.objects.get(hirer = service.owner, worker = service.service_provided.worker)
            items = evaluation.core_worker_evaluation.all()
            for item in items:
                if item.item is Worker_Evaluation_items.punctuality:
                    params['punctuality'] = item.value
                elif item.item is Worker_Evaluation_items.quality:
                    params['quality']= item.value
                elif item.item is Worker_Evaluation_items.trust:
                    params['trust'] = item.value
                elif item.item is Worker_Evaluation_items.cost_benefit:
                    params['cost_benefit'] = item.value
        except WorkerEvaluation.DoesNotExist:
            init_value = 3
            params['punctuality'] = init_value
            params['quality'] = init_value
            params['trust'] = init_value
            params['cost_benefit'] = init_value
        form = EvaluationForm(initial=params)
        params = {'service': service, 'form': form}
        return render(request, 'partials/_evaluate_worker.html', params)


@login_required
def evaluate_service(request, id):
    """
    Evaluate the worker and finish the service.

    This method is called via ajax by schedule to finalize a job and evaluate
    in general the worker. Receive the service id as 'id' parameter.
    """
    service = get_object_or_404(ServiceRequest, pk=id)
    worker = service.service_provided.worker
    if request.method == 'GET':
        # Checks if already exists some recommendation from current logged user
        # to evaluated professional.
        if (WorkerEvaluation.objects.filter(hirer=request.user, worker=worker).exists()):
            # return form with current evaluation
            evaluation = WorkerEvaluation.objects.get(hirer=request.user, worker=worker)
            form = EvaluationProfessionalForm(instance=evaluation)
        else:
            form = EvaluationProfessionalForm()

    elif request.method == 'POST':
        evaluation = None
        if WorkerEvaluation.objects.filter(hirer=request.user, worker=worker).exists():
            evaluation = WorkerEvaluation.objects.get(hirer=request.user, worker=worker)

        form = EvaluationProfessionalForm(request.POST or None, instance=evaluation)
        print(form.data)

        if form.is_valid():
            we = form.save(commit=False)
            we.hirer = request.user
            we.worker = worker
            we.status = 'A'
            we.save()

            if we.recommend:
                Endorsment.apply(we.hirer, we.worker)
            else:
                Endorsment.remove(we.hirer, we.worker)

            service.status = Service_Request_Status.finished
            service.save()
            notification = Notification.objects.requestRejected(
                service.service_provided.worker, "NOVA AVALIAÇÃO: " +
                service.owner.get_full_name() + " avaliou seu perfil.")
            notification.save()
            # Send new evaluation alert by email
            send_mail(
                "[Indikko] Alerta de Nova Avaliação", alert_worker_evaluated(we.hirer, we.worker),
                'suporte@indikko.com', [we.worker.email], fail_silently=True)
            # Send service changed alert by email
            send_mail(
                "[Indikko] Alerta Alteração do Estado do Serviço", alert_service_notification(we.worker, service),
                'suporte@indikko.com', [we.worker.email], fail_silently=True)

            return redirect('hirer:home')

    if request.is_ajax():
        return render(
            request, 'partials/_evaluate-professional.html',
            {'form': form, 'worker': worker, 'service': service})
    else:
        return render(
            request, 'hirer/evaluate-professional.html',
            {'form': form, 'worker': worker})


@login_required
def evaluate_worker_ex(request, id):
    """
    Create or update a worker evaluation/recommendation.

    This method works with fixed set of genercic questions about the worker.
    """
    worker = IndicoUser.objects.get(pk=id)
    if request.method == 'GET':
        # Checks if already exists some recommendation from current logged user
        # to evaluated professional.
        if (WorkerEvaluation.objects.filter(
           hirer=request.user, worker=worker).exists()):
            # return form with current evaluation
            evaluation = WorkerEvaluation.objects.get(
               hirer=request.user, worker=worker)
            form = EvaluationProfessionalForm(instance=evaluation)
        else:

hirer/templates/partials/_evaluate-professional.html
<section id="evaluate_worker" class="no-margin">
  <div class="container">
    <div class="row">
      <div class="col-sm-6" style="float: none; margin: 0 auto;">
        <div class="row recommend-header">
            <div class="col-sm-2 ">
              <img src="{% if worker.photo %}{{worker.photo.url}}{% else %}https://s3.amazonaws.com/indicoapp/1467106865_silhouette5.png{% endif %}" class="img-responsive"/>
            </div>
            <div class="col-sm-10">
              <h2>{{worker.get_full_name}}</h2>
            </div>
        </div>

        <div class="row">
          <form method="post" action="{% url 'hirer:finish-service' service.id %}">{% csrf_token %}
            <div class="form-group">
              <label class="col-sm-7 control-label">Pontualidade</label>
              {% for choice in form.punctuality.field.choices %}
              <label class="radio-inline">
                <input name='{{ form.punctuality.name }}'
                   id='{{ form.punctuality.auto_id }}_{{ forloop.counter0 }}' type='radio' value='{{ choice.0 }}'
                   {% ifequal form.punctuality.value choice.0 %} checked='checked'{% endifequal %}/> {{ choice.1 }}
              </label>
              {% endfor %}
            </div>

            <div class="form-group">
              <label class="col-sm-7 control-label">Habilidade</label>
              {% for choice in form.quality.field.choices %}
              <label class="radio-inline">
                <input name='{{ form.quality.name }}'
                   id='{{ form.quality.auto_id }}_{{ forloop.counter0 }}' type='radio' value='{{ choice.0 }}'
                   {% ifequal form.quality.value choice.0 %} checked='checked'{% endifequal %}/> {{ choice.1 }}
               </label>
              {% endfor %}
            </div>

            <div class="form-group">
              <label class="col-sm-7 control-label">Confiança</label>
              {% for choice in form.trust.field.choices %}
              <label class="radio-inline">
                <input name='{{ form.trust.name }}'
                   id='{{ form.trust.auto_id }}_{{ forloop.counter0 }}' type='radio' value='{{ choice.0 }}'
                   {% ifequal form.trust.value choice.0 %} checked='checked'{% endifequal %}/> {{ choice.1 }}
               </label>
              {% endfor %}
            </div>

            <div class="form-group">
              <label class="col-sm-7 control-label">Cordialidade</label>
              {% for choice in form.cost_benefit.field.choices %}
              <label class="radio-inline">
                <input name='{{ form.cost_benefit.name }}'
                   id='{{ form.cost_benefit.auto_id }}_{{ forloop.counter0 }}' type='radio' value='{{ choice.0 }}'
                   {% ifequal form.cost_benefit.value choice.0 %} checked='checked'{% endifequal %}/> {{ choice.1 }}
               </label>
              {% endfor %}
            </div>
            <div class="form-group">
              <label class="col-sm-7 control-label">Marque a caixa se recomenda esse profissional?</label>
              {{ form.recommend }}
            </div>
            <div class="form-group">
              <label class="col-sm-4 control-label" for="{{ form.testimonial.id_for_label }}">Comentário</label>
              {{ form.testimonial }}
            </div>
            <div class="form-group">
              <p>
                <input class="btn btn-radius" type="submit" value="Enviar">
                <a class="btn btn-default" href="{% url 'hirer:home' %}">Cancelar</a>
              </p>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>

hirer/templates/partials/_evaluate_worker.html
{% block details%}
<h1 class="subtitle">AVALIAÇÃO DO TRABALHADOR</h1>
<div class="col-sm-12 line-div"></div>
<div class="request-detail">
    <form method="post" class="form-indico" id="evaluation-form" action="evaluate_worker/">{% csrf_token %}
        <div>
            {% for erro in form.erros %}
            {{ erro }}
            {% endfor %}
        </div>
        <div align="center">
            <input type="hidden" name="service" value="{{service.id}}">
            <input type="hidden" name="hirer" value="{{service.owner.id}}">
            <input type="hidden" name="worker" value="{{service.professional.id}}">
            <caption id="request-id">CÓDIGO DA SOLICITAÇÃO: <span id="request-cod">{{ service.id }}</span></caption>
            <div class="profissional-avatar">
                <img src="{% if service.professional.photo %}{{service.professional.photo.url}}{% else %}https://s3.amazonaws.com/indicoapp/1467106865_silhouette5.png{% endif %}" />
            </div>
            <span>{{service.professional.first_name}}&nbsp;{{service.professional.last_name}}</span>
            <br/>
            <br/>
            <div>
                <div class="form-radio-group" align="left">
                    <label for="{{ form.punctuality.id_for_label }}">{{form.punctuality.label}}</label>
                    <br/>
                    {{form.punctuality}}
                    <p class="help-block">{{form.punctuality.help_text}}</p>
                </div>
                <div class="form-radio-group" align="left">
                    <label for="{{ form.quality.id_for_label }}">{{form.quality.label}}</label>
                    <br/>
                    {{form.quality}}
                    <p class="help-block">{{form.quality.help_text}}</p>
                </div>
                <div class="form-radio-group" align="left">
                    <label for="{{ form.trust.id_for_label }}">{{form.trust.label}}</label>
                    <br/>
                    {{form.trust}}
                    <p class="help-block">{{form.trust.help_text}}</p>
                </div>
                <div class="form-radio-group" align="left">
                    <label for="{{ form.cost_benefit.id_for_label }}">{{form.cost_benefit.label}}</label>
                    <br/>
                    {{form.cost_benefit}}
                    <p class="help-block">{{form.cost_benefit.help_text}}</p>
                </div>
            </div>
            <br/>
            <div>
                <p>VOCÊ INDICA OU NÃO INDICA O PROFISSIONAL?</p>
            </div>
        </div>
        <div class="row">
            <button class="btn btn-radius btn-recusar" form="evaluation-form" type="submit" value="False" name="indicate">NÃO INDICO</button>
            <button class="btn btn-radius pull-right" form="evaluation-form" type="submit" value="True" name="indicate">INDICO</button>
            <br />
            <br />
        </div>
    </form>
</div>
{% endblock %}

hirer/templates/partials/_hirer_friends.html
{% load staticfiles %}

<div class="common">
    <strong>{{total}} amigos</strong><br />
    <strong>3 VIP</strong>
</div>
<div class="common-social">
    {% for f in friends %}
    <img src="{{f.photo}}" />
    {% endfor %}
</div>

hirer/templates/partials/_hirer_service_day.html
{% block details%}
<h1 class="subtitle">SOLICITAÇÕES DE SERVIÇO</h1>
<div class="col-sm-12 line-div"></div>
<div class="menu-request">
    <a class="col-sm-4 btn-request-toggle" href="#" data-element="#requests-open">NOVOS</a>
    <a class="col-sm-4 btn-request-toggle" href="#" data-element="#requests-pending">AGENDADO</a>
    <a class="col-sm-4 btn-request-toggle" href="#" data-element="#requests-closed">CONCLUÍDO</a>
</div>
<div class="requests">
    <table id="requests-open" class="table">
        <caption id="requests-open-total">{{ open_services|length }} solicitações</caption>
        {% for service in open_services %}
        <tbody value="{{ service.id }}" status="{{ service.status }}">
        <tr class="request-cod">
            <th colspan="3">cód:{{service.id}}</th>
        </tr>
        <tr class="header">
            <td>PROFISSIONAL</td> <td>DATA DO SERVIÇO</td> <td>STATUS</td>
        </tr>
        <tr class="owner">
            <td>{{service.service_provided.worker.first_name}}&nbsp;{{service.service_provided.worker.last_name}}</td> <td>{{service.date}}</td> <td>{{service.get_status_display}}</td>
        </tr>
        </tbody>
        {% endfor %}
    </table>
    <table id="requests-pending" class="table">
        <caption id="requests-pending-total">{{ pending_services|length }} solicitações</caption>
        {% for service in pending_services %}
        <tbody value="{{ service.id }}" status="{{ service.status }}">
        <tr class="request-cod">
            <th colspan="3">cód:{{service.id}}</th>
        </tr>
        <tr class="header">
            <td>PROFISSIONAL</td> <td>DATA DO SERVIÇO</td> <td>STATUS</td>
        </tr>
        <tr class="owner">
            <td>{{service.service_provided.worker.first_name}}&nbsp;{{service.service_provided.worker.last_name}}</td> <td>{{service.date}}</td> <td>{{service.get_status_display}}</td>
        </tr>
        </tbody>
        {% endfor %}
    </table>
    <table id="requests-closed" class="table">
        <caption id="requests-closed-total">{{ closed_services|length }} solicitações</caption>
        {% for service in closed_services %}
        <tbody value="{{ service.id }}" status="{{ service.status }}">
        <tr class="request-cod">
            <th colspan="3">cód:{{service.id}}</th>
        </tr>
        <tr class="header">
            <td>PROFISSIONAL</td> <td>DATA DO SERVIÇO</td> <td>STATUS</td>
        </tr>
        <tr class="owner">
            <td>{{service.service_provided.worker.first_name}}&nbsp;{{service.service_provided.worker.last_name}}</td> <td>{{service.date}}</td> <td>{{service.get_status_display}}</td>
        </tr>
        </tbody>
        {% endfor %}
    </table>
</div>

{% load staticfiles %}
<script src="{% static 'js/toggle-requests.js'%}"></script>
<script>
    var item;
    $(document).ready(function() {
        $("div.requests > table > tbody").click(function() {
            var service_id = $(this).attr('value');
            var status = $(this).attr('status');
            console.log('service id: ' + service_id);
            console.log('status: ' + status);
            if (status == 6) {
                var url = '/hirer/service/end/'+service_id+'/';
                $.get(url,{id:service_id}, function(data){
                        $("#service-detail").html(data);
                    }
                );
            } else {
                $("#service-detail").html("");
            }
        });
    });
</script>
{% endblock %}