api/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from .views import *
from core.views import get_phone_ajax, rank_worker_ajax, set_status_we_ajax, send_pin_ajax
from rest_framework.urlpatterns import format_suffix_patterns

from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'categories', ServiceCategoryViewSet, 'categories')
router.register(r'users', SimpleUserView, 'users')
router.register(r'workerevaluation', WorkerEvaluationView, 'workerevaluation')
router.register(r'workers', WorkersViewSet)
router.register(r'places', PlaceViewSet, 'places')
router.register(r'phones', PhoneViewSet, 'phones')

urlpatterns = [
    # Routers urls
    url(r'^', include(router.urls)),

    # Categories
    url('^categories-resume', ServiceCategoryResume.as_view(), name='categories-resume'),

    # professionals
    url ('^professionals/(?P<id>.+)/$', ProfessionalList.as_view(), name='professionals'),
    url ('^professional/(?P<pk>.+)/$', ProfessionalDetails.as_view(), name='professional-details'),

    # User profiles
    url('^user/profile/$',LoggedUserProfile.as_view()),   

    url('^service-description/$', ServiceTypeViewSet.as_view()),
    url('^service-description/(?P<id>[0-9]+)/$', ServiceTypeSpecificViewSet.as_view()),

    # Authentication urls
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    # Templates urls
    url('^template/(?P<pk>.+)/$', EvaluationTemplateByCategory.as_view(),name="template-detail"),

    # Services urls
    url('^all-services/$',ServiceCategoryComplete.as_view()),
    url('^services/$',ServiceCategoryList.as_view()),
    url('^dateservices/(?P<mes>[0-9]+)/(?P<ano>[0-9]+)/(?P<worker>[0-1])/(?P<userId>[0-9]+)/?$', DateServiceRequestList.as_view(), name='date-service-list'),

    # Agendamentos
    url('^agendamentos/(?P<pk>.+)/$', ServiceRequestRetrieveUpdate.as_view(),name="service-details"),
    url('^agendamentos/$', ServiceRequestView.as_view(), name='agendamento-list'),
    url('^criar-agendamento/$', ServiceRequestCreateView.as_view(), name='criar-agendamento'),
    url('^todos-agendamentos/$', ServiceRequestComplete.as_view(), name='todos-agendamentos'),

    # Notifications
    url('^notifications/$', NotificationList.as_view(), name='notification-list'),
    url('^notifications/(?P<pk>.+)/$', NotificationDetails.as_view(), name='notification-details'),

    # Messages
    url('^messages/(?P<id>[0-9])/$', ServiceMessageListCreate.as_view(), name='msg-list-update'),
    url('^messages/(?P<id>[0-9])/latest/$', LatestServiceMessageList.as_view(), name='msg-latest'),
    url('^messages/(?P<pk>[0-9])/last/$', LastServiceMessage.as_view(),name="msg-last"),


    url ('^example/$', ExampleView.as_view(), name='example'),

    #Ajax
    url('^ajax/get-phone-user/$', get_phone_ajax, name='get_phone_ajax'),
    url('^ajax/rank-worker/$', rank_worker_ajax, name='rank_worker_ajax'),
    url('^ajax/set-status-we/$', set_status_we_ajax, name='set_status_we_ajax'),
    url('^ajax/send_pin_ajax/$', send_pin_ajax, name='send_pin_ajax'),
]

core/urls.py
from django.conf.urls import url, patterns
from . import views

urlpatterns = [
	url(r'^$', views.home, name='home'),
	url(r'^profissional/(?P<id>[0-9]+)/$',
        views.professional_details, name='professional-details'),
	url(r'^profissionais/(?P<category>[0-9]+)/$',
        views.professionals, name='professionals'),
	url(r'^agenda/$', views.full_schedule, name='schedule'),
    url(r'^confirmacao/sms/$', views.sms_validation, name='sms-validation'),
	url(r'^agendamento/(?P<service_provided>[0-9]+)/?$',
        views.service_request_create, name='service-request-create'),
    url(r'^endereco/$', views.address_list, name='place-list'),
    url(r'^endereco/add/$', views.address_create, name='place-create'),
    url(r'^remove/(?P<id>[0-9]+)$', views.remove_service_provide, name='remove_service_provide'),
    url(r'^remove_profession/(?P<id>[0-9]+)$', views.remove_profession, name='remove_profession'),
    url(r'^remove_workzone/(?P<id>[0-9]+)$', views.remove_workzone, name='remove_workzone'),
    url(r'^endereco/edit/(?P<id>[0-9]+)/$', views.address_update, name='place-edit'),
    url(r'^endereco/delete/(?P<id>[0-9]+)/$', views.address_delete, name='place-delete'),
    url(r'^skills/(?P<id>[0-9]+)/$', views.skills_from_category, name='skills'),
    url(r'^alertas/$', views.notifications_list, name='notifications'),
    url(r'^perfil/$', views.settings, name='settings'),
    url(r'^agenda/get_day_service/', views.get_day_service, name='get_day_service'),
    url(r'^telefone/edit/(?P<id>[0-9]+)/$', views.phone_update, name='phone-edit'),
    url(r'^telefone/delete/(?P<id>[0-9]+)/$', views.phone_delete, name='phone-delete'),
    url(r'^telefone/$', views.phone_list, name='phone-list'),
    url(r'^telefone/add/$', views.phone_create, name='phone-create'),
    url(r'^obrigado/$', views.thanks_evaluation, name='thanks_evaluation')
    
]

indico/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
import rest_auth
from hirer import views
import certbot_django.server.urls

urlpatterns = [
    # Examples:
    # url(r'^$', 'indico.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),

    url ('', include('public.urls', namespace='indico')),
    url (r'^hirer/', include('hirer.urls', namespace='hirer')),
    url (r'^profissional/', include('worker.urls', namespace='worker')),
    url (r'^usuario/', include('core.urls', namespace='core')),
    url (r'^api/v1/', include('api.urls', namespace='api_v1')),

    url(r'^reset/done/$', 'password_reset.views.reset_done', name='password_reset_done'),

    url('', include('social.apps.django_app.urls', namespace='social')),
    url('', include('django.contrib.auth.urls', namespace='auth')),
    url(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    url('', include('password_reset.urls')),
    url(r'^.well-known/acme-challenge/(?P<token>.+)/$', views.acme),
    url(r'^rest-auth/', include('rest_auth.urls')),
    url(r'^accounts/', include('allauth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
# -*- coding: utf-8 -*-


from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser, PermissionsMixin
)
from django.core.mail import send_mail
from .constants import *
import json
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Q
from django.conf import settings
from django.db.models import Avg
import math
from functools import reduce
import logging


logger = logging.getLogger(__name__)


class IndicoUserManager(BaseUserManager):
    def _create_user(self, email, password,
                     is_staff, is_superuser, **extra_fields):
        """
        Creates and saves a User with the given email and password.
        """
        now = timezone.now()
        if not email:
            email = self.normalize_email(email)
            raise ValueError('The given email must be set')
        
        user = self.model(email=email,
                          is_staff=is_staff, is_active=True,
                          is_superuser=is_superuser, last_login=now,
                          date_joined=now, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        return self._create_user(email, password, False, False,
                                 **extra_fields)

    def create_user(self, username, email=None, password=None, **extra_fields):
        """
        This override is necessary to Python Social Auth plugin works. This method
        just receive username and after ignore it.
        """
        if email == "":
            logger.error("Inside create user:" + username)
            email = username
        return self._create_user(email, password, False, False,
                               **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        return self._create_user(email, password, True, True,
                                 **extra_fields)

    def create_worker_user (self, email, password, **extra_fields):
        user = self._create_user(email, password, False, False,
                               **extra_fields)
        user.account_type = User_Types.worker
        user.save()
        return user

    def create_contractor_user (self, email, password, **extra_fields):
        user = self._create_user(email, password, False, False,
                               **extra_fields)
        user.account_type = User_Types.contractor
        user.save()
        return user

    def avaliable_workers (self, **kwargs):
        """
        Do ponto de vista do sistema e viabilidade, um trabalhador disponível
        é aquele que possui a conta de acesso ao sistema aprovada pela adminis-
        tração.
        """
        # TODO: Order_by (?) can lead poor database performance
        return self.filter(account_type=User_Types.worker).\
                    filter (account_state=Account_States.approved).order_by('?')

    def professionals_by_category (self, category = None):
        query = self.filter(account_type=User_Types.worker).\
                    filter (account_state=Account_States.approved)

        if category != None:
            query = query.filter (categories=category)

        return query.order_by('id')

    def search_professionals_by_name(self, category=None, name=None):
        query = IndicoUser.objects.filter(account_type=User_Types.worker, account_state=Account_States.approved)
        if category is not None:
            query = query.filter(categories=category)
        if name is not None:
            query = query.filter(Q(first_name__icontains=name) | Q(last_name__icontains=name))
        return query.order_by('id')


    def get_active_worker_details (self, _id):
        return self.filter(account_type=User_Types.worker).filter (account_state=Account_States.approved).filter (pk = _id)


class GroupServiceCategory(models.Model):
    description = models.CharField(
        u'descrição',
        max_length=255)

    def __str__(self):
        return self.description

    class Meta:
        verbose_name = u'Grupo (Profissão)'
        verbose_name_plural = u'Grupos (Profissão)'


class ServiceCategory(models.Model):
    """
    The categories are used inside the system to represent the diferent professions
    supported by the system.
    """
    description = models.CharField(
        u'descrição',
        max_length=100)
    image = models.FileField(
        u'imagem',
        upload_to='cat/%Y/%m/%d/', blank=True, null=True)
    is_active = models.BooleanField(u'ativo?', default=False)
    group = models.ForeignKey(
        GroupServiceCategory, 
        verbose_name=u'grupo',
        blank=True, 
        null=True)

    @classmethod
    def create (cls, description):
        category = cls(description = description)
        category.save()
        return category

    @classmethod
    def get_active_categories(cls):
        """
        Retorna todas as mensagens de um determinado serviço. Esse método é útil
        quando o usuário acessa um novo cliente (browser ou smartphone) e necessita
        atualizar a thread de conversa do serviço no dispositivo
        """
        q = ServiceCategory.objects.filter (is_active = True)
        return q

    def __str__(self):
        return self.description

    class Meta:
        verbose_name = u'Profissão'
        verbose_name_plural = u'Profissões'


class ServiceType(models.Model):
    description = models.CharField(
        u'descrição',
        max_length=255)
    service_category = models.ForeignKey(
        ServiceCategory, 
        verbose_name=u'Profissão',
        blank=False, 
        null=False)

    def __str__(self):
        return self.description

    class Meta:
        verbose_name = u'Tipo de serviço'
        verbose_name_plural = u'Tipos de serviço'


class Skill (models.Model):
    description = models.CharField(
        u'descrição',
        max_length=100)
    category = models.ForeignKey(
        ServiceCategory,
        verbose_name=u'profissão'
    )

    def __str__(self):
        return self.description

    @classmethod
    def create (cls, description, category):
        skill = cls(description = description, category = category)
        skill.save()
        return skill

    class Meta:
        verbose_name = u'Diferenciais'


class UserDocuments (models.Model):
    person_id = models.FileField(
        upload_to='doc/%Y/%m/%d/', 
        verbose_name=u'identificação pessoal',
        blank=True, 
        null=True)
    residence_proof = models.FileField(
        upload_to='doc/%Y/%m/%d/', 
        verbose_name=u'comprovante de residência',
        blank=True, 
        null=True)
    cpf = models.FileField(upload_to='doc/%Y/%m/%d/', blank=True, null=True)

    def __str__(self):
        msg = ""
        try:
            msg = "Documentos de " + self.indicouser.get_full_name()
        except ObjectDoesNotExist:
            pass

        return msg

    class Meta:
        verbose_name = u'documentos do usuário'


class WorkZone(models.Model):
    zone = models.CharField(_('zone of neighborhood'), max_length=80)
    neighborhood = models.CharField(_('neighborhood'), max_length=100)
    state = models.CharField(_('location state'), max_length=100)
    city = models.CharField(_('location city'), max_length=100)

class IndicoUser(AbstractBaseUser, PermissionsMixin):

    # Customized permissions, to implement restricted page access on the system.
    class Meta:
        permissions = (("worker_pass", "Can access as a worker"),
        ("contractor_pass", "Can access as a contractor"))
        verbose_name = u'usuário'

    # Unique account identifier & Account info
    email = models.CharField(verbose_name=_('email address'), max_length=255, unique=True,)
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)
    is_staff = models.BooleanField(_('staff status'), default=False, help_text=_('Designates whether the user can log into this admin site.'))
    is_active = models.BooleanField(
        _('active'), 
        default=True, 
        help_text=_('Designates whether this user should be treated as active. Unselect this instead of deleting accounts.'))
    is_admin = models.BooleanField(default=False)
    attendance_in_domicile = models.BooleanField(default=True)
    costumer_service = models.BooleanField(default=False)
    place_to_work = models.CharField(_('place to work'), max_length=200, blank=True)
    # Personal info
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=30, blank=True)
    date_of_birth = models.DateField(default=None, blank=True, null=True)
    profile_picture = models.TextField()
    photo = models.FileField(upload_to='profile/%Y/%m/%d/', blank=True, null=True)
    week_availability = models.TextField()
    # Account info
    facebook_id = models.BigIntegerField(default=None, blank=True, null=True)
    account_type = models.IntegerField(
        _('account type'), choices=USER_TYPE_CHOICES, default=None, blank=True, 
        null=True)
    account_state = models.IntegerField(
        _('account_state'), 
        choices=ACCOUNT_STATES_CHOICES, default=Account_States.new)
    is_terms_accepted = models.BooleanField(default=False)

    # Worker only account info
    resume = models.TextField(default=None, blank=True, null=True)
    rate = models.FloatField(default=0.0, blank=True, null=True)
    endorsements = models.IntegerField(default=0, blank=True, null=True)
    phone_number = models.CharField(
        max_length=20, default=None, blank=True, null=True)
    documents = models.OneToOneField (
        UserDocuments,default=None, blank=True, null=True,
        on_delete=models.SET_NULL)

core/templates/core/home.html
{% extends "core/base.html" %}
{% load staticfiles %}
{% block title %}Indikko - Pesquisa de profissionais{% endblock %}



{% block content %}
<style type="text/css">
    #wrapper{
        margin: 0px;
    }
    .container{
        width: 100%;
    }

    .sec-intro{
      height: 380px;
    }

    @media screen and (max-width: 768px) and (min-width: 420px){
      .sec-intro{
        height: 440px;
      }
    }

    .background-intro{
      background-size: 590px 100%;
    }

    .sec-professional{
      height: 270px;
      line-height: 26px;
    }

    .search-bar{
      width: 50%;
      margin-left: 21.495%;
    }


</style>
<div class="container">
  <div class="background-intro">
    <section id="intro" class="sec-intro">
      <div class="landing-header">
          <!--##################################POPUP Login######################################## -->
          
          <!--##################################POPUP Login - END######################################## -->
          <p style="text-align: center;">
            <strong>Encontre aqui a melhor indicação para</strong></p>
            <p style="text-align: center;">aquele serviço que você tanto precisa.</p>
            <p style="text-align: center;"> Agende-se!
            </p>
            <div class="search-region">
              <div class="row">

                <input class="search-bar" id="search-text" type="text" maxlength="31" name="search-bar"  placeholder="Busque seu profissional...">

                <a id="search-link" href="#"><img class="search-button" src="{% static 'images/magn.png'%}" border="0" alt="Submit" /></a>
              </div>
            </div>
            <script type="text/javascript">
              var categoriesID = [];

                      $(function() {
                        
                        var availableCategories = [
                          {% for c in all_categories%}
                            '{{c.description}}',
                          {% endfor%}
                        ];
                        {% for c in all_categories%}
                          categoriesID.push({key: "{{c.description}}", value: "{{c.id}}"});
                        {% endfor%}
                        $("#search-text").autocomplete({
                          source: availableCategories

                        });
                      });

                      $("#search-text").autocomplete({
                          select: function (a, b) {
                              for (var i = 0; i < categoriesID.length; i++) {
                                if (categoriesID[i].key == b.item.value) {
                                  console.log(categoriesID[i].value);
                                  
                                  document.getElementById("search-link").href="/usuario/profissionais/" + categoriesID[i].value + "/"; 
                                }
                              }
                          }
                      });
            </script>
          </div>  
        </div>
      </section>
      <section id="sec-professional" class="sec-professional">
      <div class="professional">
        <h1>Seja um <strong>Profissional!</strong></h1>  
        <p>Nossa lista de profissionais funciona com indicações boca a boca de modo virtual, com base</p><p><strong>
        nas avaliações que seus clientes passam e o indicam para todos seus amigos do Facebook.</strong></p>
      </div>
    </section>
    <section id="sec-our-services" class="sec-our-services">
       <div class="background-our-service">
        <div class="our-services"><p>Encontre prestadores de serviços</p><p><strong>avaliados por seus amigos...</strong></p>
          <div class="row">
            {% for group, categories in groups.items %}
                {% for c in categories %}
                    {% if forloop.counter|divisibleby:3 %}
                    </div>
                    <div class="row">
                    {% endif %}
                    <div class="col-sm-6" name="{{c.description}}">
                      <a href="{% url 'core:professionals' c.id %}">
                        {% if c.image %}
                        <img style="width: 300px ;margin: 0px auto;" class="image-service" src="{{ c.image.url }}" />
                        {% else %}
                        <img style="width: 300px ;margin: 0px auto;" class="image-service" src="{% static 'images/category-placeholder.png'%}" />
                        {% endif %}
                      </a>
                      <p><strong>{{c.description}}</strong></p>
                    </div>
                    {% if forloop.counter|divisibleby:4 %}
                    </div>
                    {% endif %}
                {% endfor %}
            {% endfor %}
          </div>
        </div>
      </div>
    </section>
    <section id="sec-last" class="sec-last">

        <div class="col-sm-9">
          <div class="row">
            <a href="#" class="featured-text links"><strong>Seja um profissional</strong></a>
          </div>
          <div class="row">
            <a href="#" class="links">Quem somos</a>
          </div>
          <div class="row">
            <a href="#" class="links">Nossos profissionais</a>
          </div>
        </div>
        <div class="col-sm-3">
          <div class="row featured-text"><strong>SIGA-NOS!</strong></div>
          <div class="row">
            <a  href="https://www.instagram.com/indikko/"><img src="{% static 'images/icon-instagram.png'%}"></a>
            <a  href="https://www.facebook.com/Indikko/"><img src="{% static 'images/icon-facebook.png'%}"></a>
            <a href="mailto:suporte@indikko.com"><img src="{% static 'images/icon-email.png'%}"></a>
          </div>
        </section>
</div>
	{% if groups %}
        
    {% else %}
        <img src="{% static 'images/congratulations.JPG' %}" />
    {% endif %}

{% endblock %}

core/templates/core/phone-edit.html
{% extends "core/base.html" %}
{% block title %}Indikko{% endblock %}

{% block content %}

{% load app_extras %}

<style type="text/css">
  #id_number{
    width: 200px;
    font-size: 18px;
  }
  label{
    font-size: 18px;
  }
</style>

<section id="servicerequest" class="no-margin">
  <div class="container">
      <h3>Informe seu telefone</h3>
      {{ form.non_field_errors }}
      <form method="POST" class="form-indico">
          <div class="row">
            <div class="col-sm-2">
              {% csrf_token %}
              <label>Telefone</label>
            </div>
            <div class="col-sm-8">
            <div class="form-group">
              {{ form.number }}
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-3">
              <input type="submit" value="Salvar" class="btn btn-radius pull-right"/>
            </div>
          </div>
      </form>
  </div>
</section>

<script type="text/javascript">
  $("#id_number").mask("(99) 99999-9999");
</script>

{% endblock %}

core/templates/core/phone-list.html
{% extends "core/base.html" %}
{% block title %}Indikko - Endereços{% endblock %}

{% block content %}

<section id="servicerequest" class="no-margin">
  <div class="container">
    <div class="row">
      <h3>Telefones</h3>

			{% if phones%}
			 {% for phone in phones %}
       <div class="places-wrap col-sm-8">
         <div class="row">
           <div class="col-sm-10">
             <h2>{{ phone.number }}</h2>
           </div>
           <div class="col-sm-2" style="padding-top: 58px;">
             <a href="{%url 'core:phone-edit' phone.id %}"><i class="fa fa-pencil-square-o fa-2x"></i>&nbsp;&nbsp;</a>
             <a href="{%url 'core:phone-delete' phone.id %}"><i class="fa fa-trash-o fa-2x"></i></a>
           </div>
         </div>
       </div>
			 {% endfor %}
			{% else %}
        <h3>Você não possui números de telefone.</h3>
			{% endif %}

    </div>
    <div class="row">
      <a class="btn-add-local" href="{%url 'core:phone-create' %}">ADICIONAR NOVO NÚMERO</a>
    </div>
  </div>
</section>


{% endblock %}

core/templates/core/place-list.html
{% extends "core/base.html" %}
{% block title %}Indikko - Endereços{% endblock %}

{% block content %}

<section id="servicerequest" class="no-margin">
  <div class="container">
    <div class="row">
      <h3>ENDEREÇOS</h3>

			{% if places%}
			 {% for place in places %}
       <div class="places-wrap col-sm-8">
         <div class="row">
           <div class="col-sm-10">
             <h2>{{ place.label }}</h2>
             <h3>{{ place.full_address }}</h3>
           </div>
           <div class="col-sm-2" style="padding-top: 58px;">
             <a href="{%url 'core:place-edit' place.id %}"><i class="fa fa-pencil-square-o fa-2x"></i>&nbsp;&nbsp;</a>
             <a href="{%url 'core:place-delete' place.id %}"><i class="fa fa-trash-o fa-2x"></i></a>
           </div>
         </div>
       </div>
			 {% endfor %}
			{% else %}
        <h3>Nenhum endereço encontrado!</h3>
			{% endif %}

    </div>
    <div class="row">
      <a class="btn-add-local" href="{%url 'core:place-create' %}">ADICIONAR NOVO ENDEREÇO</a>
    </div>
  </div>
</section>


{% endblock %}

core/templates/core/servicerequest-create.html
{% extends "core/base.html" %}
{% block title %}Indikko - Agendamento{% endblock %}
{% block content %}
{% load staticfiles %}
{% load app_extras %}

{% load l10n %}

<link href="{% static 'css/bootstrap-datepicker.min.css'%}" rel="stylesheet">
<link href="{% static 'css/bootstrap-timepicker.min.css'%}" rel="stylesheet"/>
<section id="servicerequest" class="no-margin">
  <div class="container">
    <h1 class="subtitle">AGENDAMENTO</h1>
    <div class="col-sm-12 line-div"></div>
    <div class="row">
      <form method="post" >
        <input id="id_owner" name="owner" value="{{form.owner.value}}" type="hidden">
        <input id="id_professional" name="professional" value="{{form.professional.value}}" type="hidden">
        <input id="id_category" name="category" value="{{form.category.value}}" type="hidden">
        <input id="id_service_provided" name="service_provided" value="{{form.service_provided.value}}" type="hidden">
        <input id="id_price" name="price"
            {% localize off %}
          value="{{form.price.value}}" {% endlocalize %} type="hidden">
      <div class="col-md-2">
        <p>
          <img src="{% if p.photo %}{{p.photo.url}}{% else %}https://s3.amazonaws.com/indicoapp/1467106865_silhouette5.png{% endif %}" class="img-responsive"/>
        </p>
      </div>
      <div class="col-md-4">
        <H1>{{p.get_full_name}}</h1>
        <p>Valor do Serviço<br/>
        <span style="font-size: 1.5em;">R$ {{sp.price}}</span></p>
      </div>
      <div class="col-md-6">



          {% csrf_token %}
          {{ form.non_field_errors }}
          <div class="form-group">
            {{ form.date.errors }}
            <label for="{{ form.date.id_for_label }}">Data</label>
            <div class="input-group date">
              <!--input type="text" name="date"-->{{ form.date }}<span class="input-group-addon"><i class="glyphicon glyphicon-th"></i></span>
            </div>
          </div>
          <div class="form-group">
            {{ form.time.errors }}
            <label for="{{ form.time.id_for_label }}">Hora</label>

            <div class="input-group bootstrap-timepicker timepicker">
              <input id="id_time" type="text" name="time" class="form-control">
              <span class="input-group-addon"><i class="glyphicon glyphicon-time"></i></span>
            </div>

          </div>
          <div class="form-group">
            {% if worker.attendance_in_domicile %}
            <input type="checkbox" id="costumer_service"> Desejo atendimento em domicílio.
            <div id="address_section">
              <label for="{{ form.address.id_for_label }}">Endereço*</label>
              {{ form.address }}
            </div>
            {% endif %}
          </div>
          <div class="form-group">
            {{ form.phone_number.errors }}
            <label for="{{ form.phone_number.id_for_label }}">Informe seu telefone</label>
            {{ form.phone_number }}
          </div>

          <div class="form-group">
            {{ form.more_info.errors }}
            <label for="{{ form.more_info.id_for_label }}"></label>
            {{ form.more_info }}
          </div>
          <div class="form-group" >
            <!--{{ form.payment_preference.errors }}-->
            <label for="{{ form.payment_preference.id_for_label }} " style="visibility: hidden;" value:"Dinheiro">Forma de pagamento</label>
            {{ form.payment_preference | attr:"style=visibility: hidden;" }}
          </div>
          <div class="form-field">
            <input type="submit" value="Solicitar" class="btn btn-radius pull-right"/>
          </div>
      </div>
      </form>
    </div>
  </div>

</section>

{% endblock %}

{% block jsBlock %}
<script src="{% static 'js/bootstrap-datepicker.min.js'%}"></script>
<script src="{% static 'locales/bootstrap-datepicker.pt-BR.min.js'%}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap-timepicker.min.js' %}"></script>
<script>

  $('#id_date').datepicker({
    format: "dd/mm/yyyy",
    startDate: "today",
    todayBtn: "linked",
    language: "pt-BR",
    autoclose: true,

  });
  $('#address_section').hide();
  $('#costumer_service').change(function () {
    if ($(this).is(':checked')) {
      $('#address_section').show();
    }else{
      $('#address_section').hide();
    }
  });

  $('#id_time').timepicker({
    showMeridian : false,
    maxHours : 24,
  });
</script>
{% endblock %}

core/templates/core/sms-validation.html
{% extends "core/base.html" %}
{% load staticfiles %}
{% block title %}Indikko - Pesquisa de profissionais{% endblock %}

{% block content %}
<form method="post">
{% csrf_token %}
{{form.mobile_number}}
<button class="btn" type="button" onClick="send_pin()"><i class="icon-share"></i> Get PIN</button>
{{form.pin}}
<button class="btn" type="submit"><i class="icon-share"></i> Validar!</button>
</form>

{% endblock %}
{% block jsBlock %}
    <script type="text/javascript">
        function send_pin() {
            $.ajax({
                url: "{% url 'api_v1:send_pin_ajax' %}",
                type: "GET",
                data: { mobile_number:  $("#id_mobile_number").val() },
            })
            .done(function(data) {
                alert("PIN sent via SMS!");
            })
            .fail(function(jqXHR, textStatus, errorThrown) {
                alert(errorThrown + ' : ' + jqXHR.responseText);
            });
        }
    </script>
{% endblock %}

core/templates/core/social-exception.html
{% extends 'base.html' %}
{% block title %}Indikko - Configurações{% endblock %}

{% block content %}
{% load app_extras %}

<div class="row-centered">

	<p class="lead" style="display: inline-block; width: 500px;">
		Ocorreu um erro na autenticação do usuário do indico. Entre em contato com suporte@indikko.com para maiores informações</p>
	<p class="text-danger">
		{{message}}
	</p>
</div>
{% endblock %}