api/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from .views import *
from core.views import get_phone_ajax, rank_worker_ajax, set_status_we_ajax, send_pin_ajax
from rest_framework.urlpatterns import format_suffix_patterns

from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'categories', ServiceCategoryViewSet, 'categories')
router.register(r'users', SimpleUserView, 'users')
router.register(r'workerevaluation', WorkerEvaluationView, 'workerevaluation')
router.register(r'workers', WorkersViewSet)
router.register(r'places', PlaceViewSet, 'places')
router.register(r'phones', PhoneViewSet, 'phones')

urlpatterns = [
    # Routers urls
    url(r'^', include(router.urls)),

    # Categories
    url('^categories-resume', ServiceCategoryResume.as_view(), name='categories-resume'),

    # professionals
    url ('^professionals/(?P<id>.+)/$', ProfessionalList.as_view(), name='professionals'),
    url ('^professional/(?P<pk>.+)/$', ProfessionalDetails.as_view(), name='professional-details'),

    # User profiles
    url('^user/profile/$',LoggedUserProfile.as_view()),   

    url('^service-description/$', ServiceTypeViewSet.as_view()),
    url('^service-description/(?P<id>[0-9]+)/$', ServiceTypeSpecificViewSet.as_view()),

    # Authentication urls
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    # Templates urls
    url('^template/(?P<pk>.+)/$', EvaluationTemplateByCategory.as_view(),name="template-detail"),

    # Services urls
    url('^all-services/$',ServiceCategoryComplete.as_view()),
    url('^services/$',ServiceCategoryList.as_view()),
    url('^dateservices/(?P<mes>[0-9]+)/(?P<ano>[0-9]+)/(?P<worker>[0-1])/(?P<userId>[0-9]+)/?$', DateServiceRequestList.as_view(), name='date-service-list'),

    # Agendamentos
    url('^agendamentos/(?P<pk>.+)/$', ServiceRequestRetrieveUpdate.as_view(),name="service-details"),
    url('^agendamentos/$', ServiceRequestView.as_view(), name='agendamento-list'),
    url('^criar-agendamento/$', ServiceRequestCreateView.as_view(), name='criar-agendamento'),
    url('^todos-agendamentos/$', ServiceRequestComplete.as_view(), name='todos-agendamentos'),

    # Notifications
    url('^notifications/$', NotificationList.as_view(), name='notification-list'),
    url('^notifications/(?P<pk>.+)/$', NotificationDetails.as_view(), name='notification-details'),

    # Messages
    url('^messages/(?P<id>[0-9])/$', ServiceMessageListCreate.as_view(), name='msg-list-update'),
    url('^messages/(?P<id>[0-9])/latest/$', LatestServiceMessageList.as_view(), name='msg-latest'),
    url('^messages/(?P<pk>[0-9])/last/$', LastServiceMessage.as_view(),name="msg-last"),


    url ('^example/$', ExampleView.as_view(), name='example'),

    #Ajax
    url('^ajax/get-phone-user/$', get_phone_ajax, name='get_phone_ajax'),
    url('^ajax/rank-worker/$', rank_worker_ajax, name='rank_worker_ajax'),
    url('^ajax/set-status-we/$', set_status_we_ajax, name='set_status_we_ajax'),
    url('^ajax/send_pin_ajax/$', send_pin_ajax, name='send_pin_ajax'),
]

core/urls.py
from django.conf.urls import url, patterns
from . import views

urlpatterns = [
	url(r'^$', views.home, name='home'),
	url(r'^profissional/(?P<id>[0-9]+)/$',
        views.professional_details, name='professional-details'),
	url(r'^profissionais/(?P<category>[0-9]+)/$',
        views.professionals, name='professionals'),
	url(r'^agenda/$', views.full_schedule, name='schedule'),
    url(r'^confirmacao/sms/$', views.sms_validation, name='sms-validation'),
	url(r'^agendamento/(?P<service_provided>[0-9]+)/?$',
        views.service_request_create, name='service-request-create'),
    url(r'^endereco/$', views.address_list, name='place-list'),
    url(r'^endereco/add/$', views.address_create, name='place-create'),
    url(r'^remove/(?P<id>[0-9]+)$', views.remove_service_provide, name='remove_service_provide'),
    url(r'^remove_profession/(?P<id>[0-9]+)$', views.remove_profession, name='remove_profession'),
    url(r'^remove_workzone/(?P<id>[0-9]+)$', views.remove_workzone, name='remove_workzone'),
    url(r'^endereco/edit/(?P<id>[0-9]+)/$', views.address_update, name='place-edit'),
    url(r'^endereco/delete/(?P<id>[0-9]+)/$', views.address_delete, name='place-delete'),
    url(r'^skills/(?P<id>[0-9]+)/$', views.skills_from_category, name='skills'),
    url(r'^alertas/$', views.notifications_list, name='notifications'),
    url(r'^perfil/$', views.settings, name='settings'),
    url(r'^agenda/get_day_service/', views.get_day_service, name='get_day_service'),
    url(r'^telefone/edit/(?P<id>[0-9]+)/$', views.phone_update, name='phone-edit'),
    url(r'^telefone/delete/(?P<id>[0-9]+)/$', views.phone_delete, name='phone-delete'),
    url(r'^telefone/$', views.phone_list, name='phone-list'),
    url(r'^telefone/add/$', views.phone_create, name='phone-create'),
    url(r'^obrigado/$', views.thanks_evaluation, name='thanks_evaluation')
    
]

indico/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
import rest_auth
from hirer import views
import certbot_django.server.urls

urlpatterns = [
    # Examples:
    # url(r'^$', 'indico.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),

    url ('', include('public.urls', namespace='indico')),
    url (r'^hirer/', include('hirer.urls', namespace='hirer')),
    url (r'^profissional/', include('worker.urls', namespace='worker')),
    url (r'^usuario/', include('core.urls', namespace='core')),
    url (r'^api/v1/', include('api.urls', namespace='api_v1')),

    url(r'^reset/done/$', 'password_reset.views.reset_done', name='password_reset_done'),

    url('', include('social.apps.django_app.urls', namespace='social')),
    url('', include('django.contrib.auth.urls', namespace='auth')),
    url(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    url('', include('password_reset.urls')),
    url(r'^.well-known/acme-challenge/(?P<token>.+)/$', views.acme),
    url(r'^rest-auth/', include('rest_auth.urls')),
    url(r'^accounts/', include('allauth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

worker/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^subscription/', views.worker_subscription_form, name='subscription'),
    url(r'^set_service_status/', views.set_service_status, name='set_service_status'),
    url(r'^get_day_service/', views.get_day_service, name='get_day_service'),
    url(r'^get_service_table_day/', views.get_service_table_day, name='get_service_table_day'),
]

core/forms.py
# -*- coding: utf-8 -*-
from django import forms
from .models import IndicoUser,EvaluationParameter,EvaluationTemplateItem,ServiceRequest,Place, \
                    Skill, ServiceCategory, Reference, ServiceType, ServiceProvided, PhoneNumber, WorkZone
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.utils.translation import ugettext_lazy as _
from bootstrap3_datetime.widgets import DateTimePicker

class UserCreationForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = IndicoUser
        fields = ('email', 'date_of_birth')

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

class UserChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = IndicoUser
        fields = ('email', 'password', 'date_of_birth', 'is_active', 'is_admin')

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]

class EvaluationParameterForm(forms.ModelForm):
    class Meta:
        model = EvaluationParameter
        fields = ("description","value")

class EvaluationTemplateItemForm(forms.ModelForm):
    class Meta:
        model = EvaluationTemplateItem
        fields = ("description","min_value","max_value")

class PhoneForm(forms.ModelForm):
    number = forms.CharField(label='Telefone', max_length=20)
    class Meta:
        model = PhoneNumber
        fields = ["number"]
            
    

class PlaceForm(forms.ModelForm):
    zipcode = forms.CharField(label='CEP', widget = forms.TextInput(attrs = {'class': 'required', 'onblur' : "find_cep(this.value);"}))

    class Meta:
        model=Place
        fields=['label','street','number', 'zipcode', 'show_on_map','complement','neighborhood','city','state']
        #exclude=['owner']

class WorkerSubscriptionForm(forms.Form):
    phone = forms.CharField(label='Telefone pessoal', widget=forms.TextInput(attrs={'class': 'required form-control', 'placeholder':'(92) 99932 5544'}))
    category = forms.ModelChoiceField(label = 'Profissão', queryset=ServiceCategory.objects.all(),widget=forms.Select(attrs={'class': 'required form-control'}))

    reference_name1 = forms.CharField(widget=forms.TextInput(attrs={'class': 'required form-control', 'placeholder':'Nome'}))
    reference_name2 = forms.CharField(widget=forms.TextInput(attrs={'class': 'required form-control', 'placeholder':'Nome'}))
    reference_name3 = forms.CharField(widget=forms.TextInput(attrs={'class': 'required form-control', 'placeholder':'Nome'}))

    reference_phone1 = forms.CharField(widget=forms.TextInput(attrs={'class': 'required form-control', 'placeholder':'(92) 99932 5544'}))
    reference_phone2 = forms.CharField(widget=forms.TextInput(attrs={'class': 'required form-control', 'placeholder':'(92) 99932 5544'}))
    reference_phone3 = forms.CharField(widget=forms.TextInput(attrs={'class': 'required form-control', 'placeholder':'(92) 99932 5544'}))

    resume = forms.CharField(label='Resumo profissional',required=False,widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder':'Fale um pouco sobre suas habilidades.','maxlength':'149','rows':'3'}))

    id_doc = forms.FileField (label='Documento de identidade', help_text='RG, CNH, Identidade profissional',widget=forms.FileInput(attrs={'class': 'required'}))
    cpf_doc = forms.FileField (label='CPF/CNPJ', help_text='Se não constar no documento de identidade.')
    address_proof = forms.FileField (label='Comprovante de endereço', help_text='Comprovante de água, luz, telefone, etc...',widget=forms.FileInput(attrs={'class': 'required'}))
    accept_tc = forms.BooleanField(label='')

    skills = forms.ModelMultipleChoiceField (
        queryset = Skill.objects.all(),
        widget = forms.CheckboxSelectMultiple,
    )

class SkillTemplateItemForm(forms.ModelForm):
    class Meta:
        model = Skill
        fields = ("description",)

class ReferenceTemplateItemForm(forms.ModelForm):
    class Meta:
        model = Reference
        fields = ("name", 'phone_number')


class ProfilePhotoForm(forms.Form):
    docfile = forms.FileField(
        label='Selecione um arquivo',
        help_text='max. 2 megabytes'
    )
    


class ServiceProvidedForm(forms.Form):
    service_type = forms.ModelChoiceField(label = 'Tipo de serviço', 
        required=True, queryset=ServiceType.objects.all(), widget=forms.Select(attrs={'class': 'required form-control'}))
    duration = forms.IntegerField(required=True,  min_value=0, widget=forms.NumberInput(attrs={'class': 'required form-control'}))
    fixed_price = forms.BooleanField(required=False)
    price = forms.DecimalField(min_value=0, max_digits=6, decimal_places=2, widget=forms.NumberInput(attrs={'class': 'required form-control'}))
    
    def __init__(self, worker=None, **kwargs):
        super(ServiceProvidedForm, self).__init__(**kwargs)
        if worker:
            self.fields['service_type'].queryset = ServiceType.objects.filter(service_category__workers=worker).order_by('description')


class ServiceRequestForm (forms.ModelForm):
    date = forms.DateField(('%d/%m/%Y',),widget=forms.DateTimeInput(format='%d/%m/%Y', attrs={'class': 'form-control','placeholder':'Informe a data para realização do trabalho.'}))
    more_info = forms.CharField(widget=forms.Textarea(attrs={'placeholder':'Adicione aqui detalhes relevantes sobre o trabalho.','maxlength':'255','rows':'3', 'class':'form-control'}),required=False)
    phone_number = forms.CharField(label='Telefone pessoal', widget=forms.TextInput(attrs={'class': 'required form-control', 'placeholder':'(92) 99932 5544'}))
    values = [('1', 'Dinheiro'),('2','Cartão de Crédito')]
    payment_preference = forms.ChoiceField(choices=values, label="Forma de Pagamento")
        
    class Meta:
        model = ServiceRequest
        fields = ('date','time','payment_preference','address','owner','service_provided','price','more_info', 'phone_number')
        widgets = {'owner': forms.HiddenInput(),
                   'price': forms.HiddenInput(),
                   'address':forms.Select(attrs={'class': 'form-control'}),
                    }

    def __init__(self, owner=None, **kwargs):
        super(ServiceRequestForm, self).__init__(**kwargs)
        if owner:
            self.fields['address'].queryset = Place.objects.filter(owner=owner)


class CategoriesForm(forms.Form):
    category = forms.ModelChoiceField(label = 'Profissão', queryset=ServiceCategory.objects.all(),widget=forms.Select(attrs={'class': 'required form-control'}))
    

class SkillForm(forms.Form):
    skills = forms.ModelMultipleChoiceField (
        queryset = Skill.objects.all(),
        widget = forms.CheckboxSelectMultiple,
    )
        

class DomicileForm(forms.Form):
    validate = forms.CharField(label='validate')
    attendance_in_domicile = forms.BooleanField(required=False)
    costumer_service = forms.BooleanField(required=False)
    place_to_work = forms.CharField(label='Estabelecimento', required=False, widget=forms.TextInput(attrs={'placeholder':'Informe o nome do estabelecimento.'}))
            
    

class OrderForm(forms.Form):
    mobile_number = forms.CharField(widget=forms.TextInput(attrs={'class': 'required form-inline', 'placeholder':'92 99353 5353'}))
    pin = forms.IntegerField(required=True, widget=forms.NumberInput(attrs={'class': 'required form-control'}))

class AvailabilityForm(forms.Form):
    date = forms.DateTimeField(
        required=False,
        widget=DateTimePicker(options={"format": "YYYY-MM-DD HH:mm",
                                       "pickSeconds": False}))

worker/forms.py
# -*- coding: utf-8 -*-
from core.models import Skill, ServiceCategory, ServiceRequest, \
    ServiceProvided, ServiceType
from django import forms

class WorkerSubscriptionForm(forms.Form):
    category = forms.ModelChoiceField(label = 'Profissão', queryset=ServiceCategory.objects.all(),widget=forms.Select(attrs={'class': 'required form-control'}))

    resume = forms.CharField(label='Resumo profissional',required=False,widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder':'Fale um pouco sobre suas habilidades.','maxlength':'149','rows':'3'}))

    id_doc = forms.FileField (label='Documento de identidade', help_text='RG, CNH, Identidade profissional',widget=forms.FileInput(attrs={'class': 'required'}))
    cpf_doc = forms.FileField (label='CPF/CNPJ', help_text='Se não constar no documento de identidade.')
    address_proof = forms.FileField (label='Comprovante de endereço', help_text='Comprovante de água, luz, telefone, etc...',widget=forms.FileInput(attrs={'class': 'required'}))
    accept_tc = forms.BooleanField(label='')

    #skills = forms.ModelMultipleChoiceField (
    #    queryset = Skill.objects.all(),
    #    widget = forms.CheckboxSelectMultiple,
    #)

class StatusServiceResquetForm(forms.ModelForm):
    class Meta:
        model = ServiceRequest
        fields = '__all__'
        widgets = {
            'owner': forms.HiddenInput(),
            'address': forms.HiddenInput(),
            'date': forms.HiddenInput(),
            'time': forms.HiddenInput(),
            'payment_preference': forms.HiddenInput(),
            'status': forms.HiddenInput(),
            'service_provided': forms.HiddenInput(),
            'created': forms.HiddenInput(),
            'price': forms.HiddenInput(),
            'more_info': forms.HiddenInput(),
            'updated': forms.HiddenInput(),
        }

worker/templates/worker/base.html
{% extends 'real_base.html' %}

{% load staticfiles %}

{% block allhead %}
<title>Indikko</title>

<!-- core CSS -->
  <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet">
  <link href="{% static 'css/bootstrap-social.css'%}" rel="stylesheet">
  <link href="{% static 'css/font-awesome.min.css'%}" rel="stylesheet">
  <link href="{% static 'css/animate.min.css'%}" rel="stylesheet">
  <link href="{% static 'css/prettyPhoto.css'%}" rel="stylesheet">
  <link href="{% static 'css/main.css'%}" rel="stylesheet">
  <link href="{% static 'css/responsive.css'%}" rel="stylesheet">
  <link href="{% static 'css/style.css'%}" rel="stylesheet">
  <!--[if lt IE 9]>
  <script src="js/html5shiv.js"></script>
  <script src="js/respond.min.js"></script>
  <![endif]-->
  <link rel="shortcut icon" href="{% static 'images/ico/favicon.ico' %}">
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{% static 'images/ico/apple-touch-icon-144-precomposed.png'%}">
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{% static 'images/ico/apple-touch-icon-114-precomposed.png'%}">
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{% static 'images/ico/apple-touch-icon-72-precomposed.png'%}">
  <link rel="apple-touch-icon-precomposed" href="{% static 'images/ico/apple-touch-icon-57-precomposed.png'%}">
{% endblock %}

{% block body %}
  <style type="text/css">
  #wrapper {
    transition: margin-left .5s;
    padding: 0px;
    margin: 0px;
    overflow: scroll;
  }
  .navbar-inverse>.container{
    width: auto;
  }
  .navbar{
    padding: 0px;
  }
  .indikko-navbar{
    margin-bottom: 15px;
    margin-top: 15px;
  }
  #nav-lines{
    display: block;
    float: left;
    margin-left: 41px;
    height: 60px;
  }
  #nav-cross{
    display: none;
    float: left;
    margin-left: 30px;
    height: 60px;
  }
  #header{
    margin-bottom: 0px;
  }
  .indikko-navbar>.row{
    text-align:center;
  }

  .indikko-logo{
    height: 60px;
    left: 45%;
    position: absolute;
  }

  .want-work{
    height: 60px;
    position: absolute;
    left: 212px;
    top: 18px;
  }
  .indikko-sin{
      height: 60px;
      position: absolute;
      left: 94.578%;
  }

  /* Mobile Screen (01)*/
  @media screen and (max-width: 548px){
    #nav-lines, #nav-cross{
      height: 22px;
      margin-left: 10px;
    }

    .want-work{
      height: 18px;
      left: 212px;
      top: 18px;
    }

    .indikko-logo{
      height: 22px;
      left: 40%;

    }

    .indikko-sin{
      height: 22px;
      left: 91.578%;
    }
  }


  /* Tablet Screen (02) */
  @media screen and (max-width: 768px) and (min-width: 548px){
    #nav-lines, #nav-cross{
    height: 42px;
      margin-left: 10px;
    }

    .want-work{
      height: 18px;
      left: 212px;
      top: 18px;
    }

    .indikko-logo{
      height: 42px;
      left: 40%;

    }

    .indikko-sin{
      height: 42px;
      left: 91.578%;
    }

  }
    /* iPad Pro Screen (03) */
  @media screen and (max-width: 1024px) and (min-width: 768px){
    .indikko-logo{
      left: 40%;
    }
    .indikko-sin{
      left: 91.578%;
    }

    #nav-lines, #nav-cross{
      margin-left: 10px;
    }

  }

  </style>

  <div id="wrapper" style="margin: 0px;">
    <header id="header">
      <nav class="navbar navbar-inverse" role="banner">
        <div class="container">
          {% if not user.is_anonymous %}
          <div id="mySidenav" class="sidenav">
            <ul class="nav top-nav navbar-account">
              <li class="dropdown">
                {% if user.is_worker %}
                  <a href="{%url 'worker:home' %}"><i class="fa fa-fw fa-calendar fa-1-4x"></i> Minha Agenda</a>
                {% else %}
                  <a href="{%url 'core:schedule' %}"><i class="fa fa-fw fa-calendar fa-1-4x"></i> Minha Agenda</a>
                {% endif %}
                <a href="{%url 'core:settings' %}"><i class="fa fa-user fa-1-4x"></i> &nbsp;
                {% if user and not user.is_anonymous %}
                  {{ user.get_full_name|default:user.email }}
                {% endif %}
                <a href="{% url 'auth:logout' %}?next={% url 'indico:home' %}"><i class="fa fa-fw fa-power-off"></i> Sair</a>
              </li>
            </ul>
          </div>
          {% else %}
          <div id="mySidenav" class="sidenav">
            <ul class="nav top-nav navbar-account">
              <li class="dropdown">
                <a href="{% url 'auth:logout' %}?next={% url 'indico:home' %}"><i class="fa fa-fw fa-power-off"></i> Sair</a>
              </li>
            </ul>
          </div>
          {% endif %}
          <div class="indikko-navbar">
            <div class="row">
                <img id="nav-lines" class="nav navbar-left top-nav " src="{%static 'images/layout/sidebar-line.png'%}" onclick="openNav()">
                <img id="nav-cross" class="nav navbar-left top-nav " src="{%static 'images/layout/sidebar-cross.png'%}" onclick="closeNav()">
                {% if not user.is_anonymous %}
                <a   href="{% url 'core:home' %}" ><img class="indikko-logo" src="{% static 'images/logo.png'%}" /></a>
                {% if not user.is_worker %}
                  <a href="{%url 'worker:subscription' %}"><img class="want-work" src="{% static 'images/layout/icon-seja-um-profissional.png' %}"></a>
                {% endif %}
                <ul>
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <img class="indikko-sin" src="{% static 'images/layout/sino-w.png' %}">
                  </a>
                  <ul id="notifications" class="dropdown-menu alert-dropdown"></ul>
                </ul>
                {% else %}
                <a  href="{% url 'core:home' %}" ><img class="indikko-logo" src="{% static 'images/logo.png'%}" /></a>
                {% endif %}
            </div>
        </div>
      </nav><!--/nav-->

          </header><!--/header-->


    <div class="container">
    {% block content %}{% endblock %}
    </div>
    <div id="push"></div>
  </div>

  <script>
	    // Comentei para fazer a página funcionar
	    //function getNotifications(){
		//	$.get('/usuario/alertas/', function (data){
	 	//	  $("#notifications").html (data);
		//	});
		//}

	    function getNotifications(){
			$.get('/usuario/alertas/', function (data){
				$("#notifications").html (data);
			});
	    }

	    $(document).ready(function(){
		    setInterval(function(){ getNotifications(); }, 2000);
	    });
      
		$("[id^='btn_set_status_accept_we_']").click(
			function(){
				var element_id = $(this).attr("id")
				var idx = element_id.slice(element_id.lastIndexOf("_")+1);
				var ret = confirm("Você confirma o ACEITE da avaliação nr."+idx+"?")

				if (ret==true){
					url = "{% url 'api_v1:set_status_we_ajax' %}";
					data = {id:idx, status:'A'};
					$.post(
						url,
						data,
						function(ret){
							if(ret=='ok'){
								$('#tr_we_pending_'+idx).remove();
							}
							else{
								alert("Falha na solicitação: "+ret);
							}
						}
					);
				}
			}
		);
		$("[id^='btn_set_status_reject_we_']").click(
			function(){
				var element_id = $(this).attr("id")
				var idx = element_id.slice(element_id.lastIndexOf("_")+1);
				var ret = confirm("Você confirma o REJEITO da avaliação nr."+idx+"?")

				if (ret==true){
					url = "{% url 'api_v1:set_status_we_ajax' %}";
					data = {id:idx, status:'R'};
					$.post(
						url,
						data,
						function(ret){
							if(ret=='ok'){
								$('#tr_we_pending_'+idx).remove();
							}
							else{
								alert("Falha na solicitação: "+ret);
							}
						}
					);
				}
			}
        );

    
          function openNav() {
            document.getElementById("mySidenav").style.width = "250px";
            var img1 = document.getElementById('nav-lines');
            var img2 = document.getElementById('nav-cross');
            var content = document.getElementById('wrapper');

      img1.style.display = "none";
      img2.style.display = "block";
            content.style.marginLeft = "250px";


          }

          /* Set the width of the side navigation to 0 */
          function closeNav() {
            document.getElementById("mySidenav").style.width = "0";
            var img1 = document.getElementById('nav-lines');
            var img2 = document.getElementById('nav-cross');
            var content = document.getElementById('wrapper');
            img1.style.display = "block";
            img2.style.display = "none";
            content.style.marginLeft = "0px";


      
          } 

          


	</script>


    {% block jsBlock %}{% endblock %}
{% endblock %}