api/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from .views import *
from core.views import get_phone_ajax, rank_worker_ajax, set_status_we_ajax, send_pin_ajax
from rest_framework.urlpatterns import format_suffix_patterns

from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'categories', ServiceCategoryViewSet, 'categories')
router.register(r'users', SimpleUserView, 'users')
router.register(r'workerevaluation', WorkerEvaluationView, 'workerevaluation')
router.register(r'workers', WorkersViewSet)
router.register(r'places', PlaceViewSet, 'places')
router.register(r'phones', PhoneViewSet, 'phones')

urlpatterns = [
    # Routers urls
    url(r'^', include(router.urls)),

    # Categories
    url('^categories-resume', ServiceCategoryResume.as_view(), name='categories-resume'),

    # professionals
    url ('^professionals/(?P<id>.+)/$', ProfessionalList.as_view(), name='professionals'),
    url ('^professional/(?P<pk>.+)/$', ProfessionalDetails.as_view(), name='professional-details'),

    # User profiles
    url('^user/profile/$',LoggedUserProfile.as_view()),   

    url('^service-description/$', ServiceTypeViewSet.as_view()),
    url('^service-description/(?P<id>[0-9]+)/$', ServiceTypeSpecificViewSet.as_view()),

    # Authentication urls
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    # Templates urls
    url('^template/(?P<pk>.+)/$', EvaluationTemplateByCategory.as_view(),name="template-detail"),

    # Services urls
    url('^all-services/$',ServiceCategoryComplete.as_view()),
    url('^services/$',ServiceCategoryList.as_view()),
    url('^dateservices/(?P<mes>[0-9]+)/(?P<ano>[0-9]+)/(?P<worker>[0-1])/(?P<userId>[0-9]+)/?$', DateServiceRequestList.as_view(), name='date-service-list'),

    # Agendamentos
    url('^agendamentos/(?P<pk>.+)/$', ServiceRequestRetrieveUpdate.as_view(),name="service-details"),
    url('^agendamentos/$', ServiceRequestView.as_view(), name='agendamento-list'),
    url('^criar-agendamento/$', ServiceRequestCreateView.as_view(), name='criar-agendamento'),
    url('^todos-agendamentos/$', ServiceRequestComplete.as_view(), name='todos-agendamentos'),

    # Notifications
    url('^notifications/$', NotificationList.as_view(), name='notification-list'),
    url('^notifications/(?P<pk>.+)/$', NotificationDetails.as_view(), name='notification-details'),

    # Messages
    url('^messages/(?P<id>[0-9])/$', ServiceMessageListCreate.as_view(), name='msg-list-update'),
    url('^messages/(?P<id>[0-9])/latest/$', LatestServiceMessageList.as_view(), name='msg-latest'),
    url('^messages/(?P<pk>[0-9])/last/$', LastServiceMessage.as_view(),name="msg-last"),


    url ('^example/$', ExampleView.as_view(), name='example'),

    #Ajax
    url('^ajax/get-phone-user/$', get_phone_ajax, name='get_phone_ajax'),
    url('^ajax/rank-worker/$', rank_worker_ajax, name='rank_worker_ajax'),
    url('^ajax/set-status-we/$', set_status_we_ajax, name='set_status_we_ajax'),
    url('^ajax/send_pin_ajax/$', send_pin_ajax, name='send_pin_ajax'),
]

hirer/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    
    url(r'^profissional/(?P<id>[0-9]+)/$',
        views.professional_details, name='professional-details'),
    url(r'^agendamento/(?P<service_provided>[0-9]+)/?$',
        views.service_request_create, name='service-request-create'),
    url(r'^profissionais/(?P<category>[0-9]+)/$',
        views.professionals, name='professionals'),
    url(r'^agenda/$', views.full_schedule, name='schedule'),
    url(r'^friend/recommendations/(?P<worker>[0-9]+)/$',
        views.friends_recommendations, name='friend-recommendations'),
    url(r'^schedule/evaluate_worker/',
        views.evaluate_worker_ex, name='evaluate_worker'),
    url(r'^service/end/(?P<id>[0-9]+)/$', views.evaluate_service,
        name='finish-service'),
    url(r'^evaluate/(?P<id>[0-9]+)/$',
        views.evaluate_worker_ex, name='evaluate'),
    url(r'^schedule/get_day_service/', views.get_day_service, name='get_day_service'),
]

indico/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
import rest_auth
from hirer import views
import certbot_django.server.urls

urlpatterns = [
    # Examples:
    # url(r'^$', 'indico.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),

    url ('', include('public.urls', namespace='indico')),
    url (r'^hirer/', include('hirer.urls', namespace='hirer')),
    url (r'^profissional/', include('worker.urls', namespace='worker')),
    url (r'^usuario/', include('core.urls', namespace='core')),
    url (r'^api/v1/', include('api.urls', namespace='api_v1')),

    url(r'^reset/done/$', 'password_reset.views.reset_done', name='password_reset_done'),

    url('', include('social.apps.django_app.urls', namespace='social')),
    url('', include('django.contrib.auth.urls', namespace='auth')),
    url(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    url('', include('password_reset.urls')),
    url(r'^.well-known/acme-challenge/(?P<token>.+)/$', views.acme),
    url(r'^rest-auth/', include('rest_auth.urls')),
    url(r'^accounts/', include('allauth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hirer/forms.py
# -*- coding: utf-8 -*-
from core.models import ServiceRequest, Place, WorkerEvaluation, WorkerEvaluationItem, IndicoUser, Endorsment, \
    Notification, ServiceCategory
from core.constants import Worker_Evaluation_items, Service_Request_Status
from django import forms
from django.db.models import Q
from django.utils.safestring import mark_safe
from django.core.mail import send_mail
from core.utils import *

class ServiceRequestForm (forms.ModelForm):
    date = forms.DateField(('%d/%m/%Y',),widget=forms.DateTimeInput(format='%d/%m/%Y', attrs={'class': 'form-control','placeholder':'Informe a data para realização do trabalho.'}))
    more_info = forms.CharField(widget=forms.Textarea(attrs={'placeholder':'Adicione aqui detalhes relevantes sobre o trabalho.','maxlength':'255','rows':'3', 'class':'form-control'}),required=False)
    phone_number = forms.CharField(label='Telefone pessoal', widget=forms.TextInput(attrs={'class': 'required form-control', 'placeholder':'(92) 99932 5544'}))
    values = [('1', 'Dinheiro'),('2','Cartão de Crédito')]
    payment_preference = forms.ChoiceField(choices=values, label="Forma de Pagamento")
        
    class Meta:
        model = ServiceRequest
        fields = ('date','time','payment_preference','address','owner','service_provided','price','more_info', 'phone_number')
        widgets = {'owner': forms.HiddenInput(),
                   'price': forms.HiddenInput(),
                   'address':forms.Select(attrs={'class': 'required form-control'}),
                    }

    def __init__(self, owner=None, **kwargs):
        super(ServiceRequestForm, self).__init__(**kwargs)
        if owner:
            self.fields['address'].queryset = Place.objects.filter(owner=owner)

class HorizontalRadioRenderer(forms.RadioSelect.renderer):
  def render(self):
    return mark_safe(u'\n'.join([u'%s\n' % w for w in self])) + "<br>"

class EvaluationForm(forms.Form):
    values = [('1','1'),('2','2'),('3','3'),('4','4'),('5','5')]
    punctuality = forms.ChoiceField(
        choices=values,
        label="Pontualidade",
        widget=forms.RadioSelect(renderer=HorizontalRadioRenderer)
    )
    quality = forms.ChoiceField(
        choices=values,
        label="Qualidade",
        widget=forms.RadioSelect(renderer=HorizontalRadioRenderer)
    )
    trust = forms.ChoiceField(
        choices=values,
        label="Confiança",
        widget=forms.RadioSelect(renderer=HorizontalRadioRenderer)
    )
    cost_benefit = forms.ChoiceField(
        choices=values,
        label="Cordialidade",
        widget=forms.RadioSelect(renderer=HorizontalRadioRenderer)
    )
    service = forms.ModelChoiceField(queryset=ServiceRequest.objects.all(), widget=forms.HiddenInput())
    indicate = forms.BooleanField(required=False, widget=forms.HiddenInput())
    hirer = forms.ModelChoiceField(queryset=IndicoUser.objects.all(), widget=forms.HiddenInput())
    worker = forms.ModelChoiceField(queryset=IndicoUser.objects.all(), widget=forms.HiddenInput())

    def save(self):
        data = self.cleaned_data
        hirer = data['hirer']
        worker = data['worker']
        try:
            evaluation = WorkerEvaluation.objects.get(hirer=hirer,worker=worker)
        except WorkerEvaluation.DoesNotExist:
            evaluation = WorkerEvaluation.create(hirer, worker)
        finally:
            items = {
                Worker_Evaluation_items.punctuality:int(data['punctuality']),
                Worker_Evaluation_items.quality: int(data['quality']),
                Worker_Evaluation_items.trust: int(data['trust']),
                Worker_Evaluation_items.cost_benefit: int(data['cost_benefit']),
            }
            for item in items.items():
                try:
                    evaluation_item = WorkerEvaluationItem.objects.get(workerEvaluation=evaluation,item=item[0])
                    evaluation_item.value = item[1]
                    evaluation_item.save()
                except WorkerEvaluationItem.DoesNotExist:
                    WorkerEvaluationItem.create(
                        evaluation,
                        item[0],
                        item[1]
                    )

        if data['indicate'] is True:
            Endorsment.apply(hirer, worker)
        else:
            Endorsment.remove(hirer, worker)
        service = data['service']
        service.status = Service_Request_Status.finished
        service.save()
        notification = Notification.objects.requestRejected(service.professional, "NOVA AVALIAÇÃO: " +
                                                            service.owner.get_full_name() + " avaliou seu perfil.")
        notification.save()
        # Send new evaluation alert by email
        send_mail(
            "[Indikko] Alerta de Nova Avaliação", alert_worker_evaluated(hirer, worker),
            'suporte@indikko.com', [worker.email], fail_silently=True)
        # Send service changed alert by email
        send_mail(
            "[Indikko] Alerta Alteração do Estado do Serviço", alert_service_notification(worker, service),
            'suporte@indikko.com', [worker.email], fail_silently=True)


class SearchWorkerForm(forms.Form):
    search_field = forms.CharField(max_length=120,required=False)
    category_id = forms.IntegerField(
        widget=forms.HiddenInput(),
        required=False
    )

    def search(self):
        value = self.data['search_field']
        category_id = self.data['category_id']
        category = ServiceCategory.objects.get(pk=category_id)
        entries = IndicoUser.objects.search_professionals_by_name(category,value)
        return entries


class EvaluationProfessionalForm(forms.ModelForm):

    class Meta:
        model = WorkerEvaluation
        fields = (
            'punctuality', 'quality', 'trust',
            'cost_benefit', 'recommend', 'testimonial', 'worker', 'hirer',)
        widgets = {
          'testimonial': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Deixe aqui sua opnião sobre o profissional.','rows':'3'}),
          'worker': forms.HiddenInput(),
          'hirer': forms.HiddenInput(),
          }

    def __init__(self, *args, **kwargs):
        super(EvaluationProfessionalForm, self).__init__(*args, **kwargs)
        self.fields['hirer'].required = False
        self.fields['worker'].required = False

worker/forms.py
# -*- coding: utf-8 -*-
from core.models import Skill, ServiceCategory, ServiceRequest, \
    ServiceProvided, ServiceType
from django import forms

class WorkerSubscriptionForm(forms.Form):
    category = forms.ModelChoiceField(label = 'Profissão', queryset=ServiceCategory.objects.all(),widget=forms.Select(attrs={'class': 'required form-control'}))

    resume = forms.CharField(label='Resumo profissional',required=False,widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder':'Fale um pouco sobre suas habilidades.','maxlength':'149','rows':'3'}))

    id_doc = forms.FileField (label='Documento de identidade', help_text='RG, CNH, Identidade profissional',widget=forms.FileInput(attrs={'class': 'required'}))
    cpf_doc = forms.FileField (label='CPF/CNPJ', help_text='Se não constar no documento de identidade.')
    address_proof = forms.FileField (label='Comprovante de endereço', help_text='Comprovante de água, luz, telefone, etc...',widget=forms.FileInput(attrs={'class': 'required'}))
    accept_tc = forms.BooleanField(label='')

    #skills = forms.ModelMultipleChoiceField (
    #    queryset = Skill.objects.all(),
    #    widget = forms.CheckboxSelectMultiple,
    #)

class StatusServiceResquetForm(forms.ModelForm):
    class Meta:
        model = ServiceRequest
        fields = '__all__'
        widgets = {
            'owner': forms.HiddenInput(),
            'address': forms.HiddenInput(),
            'date': forms.HiddenInput(),
            'time': forms.HiddenInput(),
            'payment_preference': forms.HiddenInput(),
            'status': forms.HiddenInput(),
            'service_provided': forms.HiddenInput(),
            'created': forms.HiddenInput(),
            'price': forms.HiddenInput(),
            'more_info': forms.HiddenInput(),
            'updated': forms.HiddenInput(),
        }

hirer/templates/hirer/angularjs.html
<!-- AngularJS -->
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.6/angular.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.6/i18n/angular-locale_pt-br.js"></script>

<script type="text/javascript" src="{% static 'js/angularjs/hirer/hirer.module.js' %}"></script>
<script type="text/javascript" src="{% static 'js/angularjs/hirer/services/hirer.service.js' %}"></script>
<script type="text/javascript" src="{% static 'js/angularjs/hirer/controllers/hirer.controller.js' %}"></script>

hirer/templates/hirer/evaluate-professional.html
{% extends "core/base.html" %}
{% block title %}Indikko - Pesquisa de profissionais{% endblock %}

{% block content %}
{% load staticfiles %}

<section id="evaluate_worker" class="no-margin">
  <div class="container">
    <div class="row">
      <div class="col-sm-6" style="float: none; margin: 0 auto;">
        <div class="row recommend-header">
            <div class="col-sm-2 ">
              <img src="{% if worker.photo %}{{worker.photo.url}}{% else %}https://s3.amazonaws.com/indicoapp/1467106865_silhouette5.png{% endif %}" class="img-circle"/>
            </div>
            <div class="col-sm-10">
              <h2>{{worker.get_full_name}}</h2>
            </div>
        </div>

        <div class="row">
          <form method="post">{% csrf_token %}
            <div class="form-group">
              <label class="col-sm-7 control-label">Pontualidade</label>
              {% for choice in form.punctuality.field.choices %}
              <label class="radio-inline">
                <input name='{{ form.punctuality.name }}'
                   id='{{ form.punctuality.auto_id }}_{{ forloop.counter0 }}' type='radio' value='{{ choice.0 }}'
                   {% ifequal form.punctuality.value choice.0 %} checked='checked'{% endifequal %}/> {{ choice.1 }}
              </label>
              {% endfor %}
            </div>

            <div class="form-group">
              <label class="col-sm-7 control-label">Habilidade</label>
              {% for choice in form.quality.field.choices %}
              <label class="radio-inline">
                <input name='{{ form.quality.name }}'
                   id='{{ form.quality.auto_id }}_{{ forloop.counter0 }}' type='radio' value='{{ choice.0 }}'
                   {% ifequal form.quality.value choice.0 %} checked='checked'{% endifequal %}/> {{ choice.1 }}
               </label>
              {% endfor %}
            </div>

            <div class="form-group">
              <label class="col-sm-7 control-label">Confiança</label>
              {% for choice in form.trust.field.choices %}
              <label class="radio-inline">
                <input name='{{ form.trust.name }}'
                   id='{{ form.trust.auto_id }}_{{ forloop.counter0 }}' type='radio' value='{{ choice.0 }}'
                   {% ifequal form.trust.value choice.0 %} checked='checked'{% endifequal %}/> {{ choice.1 }}
               </label>
              {% endfor %}
            </div>

            <div class="form-group">
              <label class="col-sm-7 control-label">Cordialidade</label>
              {% for choice in form.cost_benefit.field.choices %}
              <label class="radio-inline">
                <input name='{{ form.cost_benefit.name }}'
                   id='{{ form.cost_benefit.auto_id }}_{{ forloop.counter0 }}' type='radio' value='{{ choice.0 }}'
                   {% ifequal form.cost_benefit.value choice.0 %} checked='checked'{% endifequal %}/> {{ choice.1 }}
               </label>
              {% endfor %}
            </div>
            <div class="form-group">
              <label class="col-sm-4 control-label" for="{{ form.testimonial.id_for_label }}">Comentário</label>
              {{ form.testimonial }}
            </div>
            <p>
              <input class="btn btn-radius" type="submit" value="Enviar recomendação">
              <a class="btn btn-default" href="{% url 'hirer:home' %}">Cancelar</a>
            </p>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

hirer/templates/hirer/home.html
{% extends "core/base.html" %}
{% load staticfiles %}
{% block title %}Indikko - Pesquisa de profissionais{% endblock %}

{% block content %}

    {% if groups %}
        {% for group, categories in groups.items %}
            <div class="text-left">
                <h3>
                    {% if group %}
                        {{group.description}}
                    {% else %}
                        &nbsp;
                    {% endif %}
                </h3>
                <hr>
            </div>

            {% for c in categories %}
                {% if forloop.counter0 == 0 or forloop.counter0|divisibleby:4 %}
                <div class="row">
                {% endif %}
                <div class="col-md-3" style="text-align:center">
                  <a href="{% url 'hirer:professionals' c.id %}">
                    {% if c.image %}
                    <img src="{{ c.image.url }}">
                    {% else %}
                    <img src="{% static 'images/category-placeholder.png'%}">
                    {% endif %}
                    <br>{{c.description}}
                  </a>
                </div>
                {% if forloop.counter|divisibleby:4 %}
                </div>
                {% endif %}
            {% endfor %}
        {% endfor %}
    {% else %}
        <img src="{% static 'images/congratulations.JPG' %}" />
    {% endif %}

{% endblock %}

hirer/templates/hirer/professional-details.html
{% extends "core/base.html" %}
{% load staticfiles tz %}
{% block title %}Indikko - Pesquisa de profissionais{% endblock %}

{% block content %}
{% load staticfiles %}
<div class="row">
  <div class="col-md-8">
    <p>
      <img 
        class="img-responsive" 
        src="{% if worker.photo %}{{worker.photo.url}}{% else %}https://s3.amazonaws.com/indicoapp/1467106865_silhouette5.png{% endif %}"/>
    </p>
    <p>
      <h2>{{worker.get_full_name}}</h2>
      <p>
      {% for c in categoriesSet %}
      <th><strong>{{c}}</strong></th>
      {% endfor %}
      </p>
      <p>{{worker.resume}}</p>
      {% if worker.skills %}
      <h2><strong>Habilidades</strong></h2>
      <hr/>
      {% for s in worker.skills.all %}
      <li>{{s.description}}</li>
      {% endfor %}
      {% endif %}
  </p>
  {% if worker.phone_number %}
  <label for="telefone">Telefone</label>
  <input id="telefone" type="text" value="{{worker.get_phone_truncated}}" readonly="readonly"/>
  <button onclick="get_phone({{worker.id}});">Mostrar telefone</button>
  {% else %}
  <p class="warning">Não há telefone registrado</p>
  {% endif %}
    <p>
      {% if recomendacoes %}
      <h3>Amigos que recomendam</h3>
      <hr/>
      {% for f in recomendacoes %}
      <img style="width:80px;" class="img-thumbnail" src="{% if f.hirer.photo %}{{f.hirer.photo.url}}{% else %}https://s3.amazonaws.com/indicoapp/1467106865_silhouette5.png{% endif %}" />
      {% endfor %}
      {% endif %}
    </p>
    
    <p>
    {% if servicepro %}
    <h2><strong>Serviços</strong></h2>
    <hr/>
    <div class="panel-body">
    {% for s in worker.get_serviceprovided %}
    <div class="col-sm-9">
    <div class="col-sm-4">
      <span style="font-size: 2em; font-family: 'Josefin Slab', serif;">{{s.service_type.description}}</span>
    </div>
    <div class="col-sm-3">
      <img src="{% static 'images/layout/clock.png' %}" />
      <span style="color: #A8A8A8; font-size: 1.2em; font-family: 'Archivo Black', sans-serif;">{{s.duration}}</span>
      <span style="color: #A8A8A8; font-size: 1.2em; font-family: 'Archivo Black', sans-serif;"> Minutos</span>
    </div>
    <div class="col-sm-3 text-right">
      <p style="font-size: 2em; font-family: 'Josefin Slab', serif;">R$ {{s.price}}</p>
    </div>
    <div class="col-sm-2">
      <a class="btn btn-default" href="/usuario/agendamento/{{s.id}}/">AGENDAR</a>
    </div>
    </div>
    {% endfor %}
    {% endif %}
    </p>
    </div>
    <p>
      {% if evaluations %}
      <h2><strong>Avaliações</strong></h2>
      <hr/>
      {% for e in evaluations %}
      <blockquote>
        <table>
          <tr>
            <td><img style="width:80px;" class="img-thumbnail" src="{% if e.hirer.photo %}{{e.hirer.photo.url}}{% else %}https://s3.amazonaws.com/indicoapp/1467106865_silhouette5.png{% endif %}" /></td>
            <td style="vertical-align: top; padding-left: 10px; padding-top: 5px;">{{e.testimonial}}</td>
          </tr>
        </table>
        <p></p>
        <footer>
        {{e.hirer.get_full_name}}<cite title="Source Title">, Nota: {{e.partial_rate}}</cite><br />
        <cite title="Source Title">Pontualidade: {{e.punctuality}}</cite><br />
        <cite title="Source Title">Qualidade: {{e.quality}}</cite><br />
        <cite title="Source Title">Confiança: {{e.trust}}</cite><br />
        <cite title="Source Title">Preço: {{e.cost_benefit}}</cite><br />
         </footer>
      </blockquote>
      {% endfor %}
      {% endif %}
    </p>
  </div>
</div>
{% endblock %}
{% block jsBlock %}
    <script type="text/javascript">
        function get_phone(id) {
            url = "{% url 'api_v1:get_phone_ajax' %}?id="+id;
            $.get(
                url,
                function(data){
                    $('#telefone').val(data);
                }
            );
        }
    </script>
{% endblock %}

hirer/templates/hirer/servicerequest-create.html
{% extends "core/base.html" %}
{% block title %}Indikko - Agendamento{% endblock %}
{% block content %}
{% load staticfiles %}
{% load app_extras %}

{% load l10n %}

<link href="{% static 'css/bootstrap-datepicker.min.css'%}" rel="stylesheet">
<link href="{% static 'css/bootstrap-timepicker.min.css'%}" rel="stylesheet"/>
<section id="servicerequest" class="no-margin">
  <div class="container">
    <h1 class="subtitle">AGENDAMENTO</h1>
    <div class="col-sm-12 line-div"></div>
    <div class="row">
      <form method="post" >
        <input id="id_owner" name="owner" value="{{form.owner.value}}" type="hidden">
        <input id="id_professional" name="professional" value="{{form.professional.value}}" type="hidden">
        <input id="id_category" name="category" value="{{form.category.value}}" type="hidden">
        <input id="id_service_provided" name="service_provided" value="{{form.service_provided.value}}" type="hidden">
        <input id="id_price" name="price"
            {% localize off %}
          value="{{form.price.value}}" {% endlocalize %} type="hidden">
      <div class="col-md-2">
        <p>
          <img src="{% if p.photo %}{{p.photo.url}}{% else %}https://s3.amazonaws.com/indicoapp/1467106865_silhouette5.png{% endif %}" class="img-responsive"/>
        </p>
      </div>
      <div class="col-md-4">
        <H1>{{p.get_full_name}}</h1>
        <p>Valor do Serviço<br/>
        <span style="font-size: 1.5em;">R$ {{sp.price}}</span></p>
      </div>
      <div class="col-md-6">



          {% csrf_token %}
          {{ form.non_field_errors }}
          <div class="form-group">
            {{ form.date.errors }}
            <label for="{{ form.date.id_for_label }}">Data</label>
            <div class="input-group date">
              <!--input type="text" name="date"-->{{ form.date }}<span class="input-group-addon"><i class="glyphicon glyphicon-th"></i></span>
            </div>
          </div>
          <div class="form-group">
            {{ form.time.errors }}
            <label for="{{ form.time.id_for_label }}">Hora</label>

            <div class="input-group bootstrap-timepicker timepicker">
              <input id="id_time" type="text" name="time" class="form-control">
              <span class="input-group-addon"><i class="glyphicon glyphicon-time"></i></span>
            </div>

          </div>
          <div class="form-group">
            {{ form.address.errors }}
            <label for="{{ form.address.id_for_label }}">Endereço*</label>
            {{ form.address }}
          </div>
          <div class="form-group">
            {{ form.phone_number.errors }}
            <label for="{{ form.phone_number.id_for_label }}">Informe seu telefone</label>
            {{ form.phone_number }}
          </div>

          <div class="form-group">
            {{ form.more_info.errors }}
            <label for="{{ form.more_info.id_for_label }}"></label>
            {{ form.more_info }}
          </div>
          <div class="form-group" >
            <!--{{ form.payment_preference.errors }}-->
            <label for="{{ form.payment_preference.id_for_label }} " style="visibility: hidden;" value:"Dinheiro">Forma de pagamento</label>
            {{ form.payment_preference | attr:"style=visibility: hidden;" }}
          </div>
          <div class="form-field">
            <input type="submit" value="Solicitar" class="btn btn-radius pull-right"/>
          </div>
      </div>
      </form>
    </div>
  </div>

</section>

{% endblock %}

{% block jsBlock %}
<script src="{% static 'js/bootstrap-datepicker.min.js'%}"></script>
<script src="{% static 'locales/bootstrap-datepicker.pt-BR.min.js'%}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap-timepicker.min.js' %}"></script>
<script>

  $('#id_date').datepicker({
    format: "dd/mm/yyyy",
    startDate: "today",
    todayBtn: "linked",
    language: "pt-BR",
    autoclose: true,

  });

  $('#id_time').timepicker({
    showMeridian : false,
    maxHours : 24,
  });
</script>
{% endblock %}